[ To be merged in Jan] DIFI-485: remove legacy code
clicksandmortar/fingerprint pull request #148
Opened 2023-12-19 12:52 UTC by EdPutans

2023-12-19 12:53 UTC, EdPutans commented
This is likely to get ourdated if the zustand impl work goes thrrough

2024-01-02 10:45 UTC, AdenFraser requested changes

2024-01-02 10:45 UTC, AdenFraser commented on src/behaviours/Modal/TriggerModal.tsx
> +import CnMModal from './modals/StandardModal'
Can we rename this to StandardModal or just Modal?

2024-01-04 09:58 UTC, Luciam91 approved these changes

2024-01-04 12:58 UTC, AdenFraser approved these changes

2024-01-04 12:58 UTC, merged