DIFI-407: Collins conversions tracking
clicksandmortar/fingerprint pull request #87
Opened 2023-11-14 09:59 UTC by EdPutans

2023-11-14 10:23 UTC, Luciam91 requested changes

2023-11-14 10:23 UTC, Luciam91 commented on src/hooks/mab/useCollinsBookingComplete.ts
> +  Stonehouse: '/tablebooking/enquiry-form-completed'
FYI not just Stonehouse, we should get the full list of brands now

2023-11-15 09:14 UTC, EdPutans commented on src/hooks/mab/useCollinsBookingComplete.ts
> +  Stonehouse: '/tablebooking/enquiry-form-completed'
addressed

2023-11-15 09:19 UTC, Luciam91 approved these changes

2023-11-15 14:38 UTC, merged