Handle hash changes as well
clicksandmortar/fingerprint pull request #93
Opened 2023-11-16 12:50 UTC by Luciam91

2023-11-16 16:49 UTC, AdenFraser requested changes
Probably a good time to grab location search (query params) too? Incase they are changed via push state?

2023-11-17 09:13 UTC, Luciam91 commented
> Probably a good time to grab location search (query params) too? Incase they are changed via push state?

83b6ef5 Done here

2023-11-17 11:06 UTC, EdPutans commented on src/hooks/useRunOnPathChange.ts
> +      setLastCollectedHash(location.hash)
rather than having 3 pieces of state, could you test if replacing `location.pathname` with`location.href` works?

2023-11-17 11:16 UTC, EdPutans approved these changes

2023-11-20 08:47 UTC, AdenFraser approved these changes

2023-11-20 10:30 UTC, merged